In [1]:
import numpy as np

In [2]:
def operacionFila(A,fil_m,fil_piv,factor):
    A[fil_m,:]=A[fil_m,:]-factor*A[fil_piv,:]

In [3]:
def escalonaSimple(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [4]:
A = np.array([[2,3,-1],
              [0,5,4],
              [0,0,6]])
b = np.array([-7,2,18])

#x = np.linalg.solve(A,b)
#print(x)

print(A)
print(b)

[[ 2  3 -1]
 [ 0  5  4]
 [ 0  0  6]]
[-7  2 18]


In [5]:
def sustRegresiva(A,b):     #Resuelve un sistema escalonado
    N=b.shape[0]   #A y b deben ser array numpy bidimensional
    x=np.zeros((N,1))
    for i in range(N-1,-1,-1):
        x[i,0]=(b[i,0]-np.dot(A[i,i+1:N],x[i+1:N,0]))/A[i,i]    
    return x #arra bidimensional


In [6]:
def Gausselimsimple(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaSimple(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(A1,b1)
    return x #array bidimensional

In [7]:
import numpy as np
#import libreria as lib
A=np.random.rand(4,4)
#print(A)
b=np.random.rand(4,1)
#print(b)
sol=Gausselimsimple(A,b)
print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)



Solution: 
[[-4.07047481]
 [ 5.8129439 ]
 [ 6.09152462]
 [-7.55831557]]

 Residuo:
 [[-3.33066907e-16]
 [-1.11022302e-15]
 [-9.65894031e-15]
 [-1.33226763e-15]]


In [ ]:
import numpy as np
import time
#import libreria as lib
n=13
A=np.random.rand(n,n)
#print(A)
b=np.random.rand(n,1)
#print(b)

start_time=time
sol=Gausselimsimple(A,b)
print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)

Solution: 
[[-0.24619411]
 [ 0.64419582]
 [-1.63391457]
 [ 1.41710104]
 [ 1.12517142]
 [ 0.66699892]
 [-1.00375065]
 [ 0.27421056]
 [-0.69058948]
 [-1.72059837]
 [-0.11261286]
 [ 2.02328438]
 [ 1.62069445]]

 Residuo:
 [[ 0.00000000e+00]
 [-8.67361738e-17]
 [ 2.22044605e-16]
 [ 3.88578059e-16]
 [-3.60822483e-16]
 [ 0.00000000e+00]
 [-2.66453526e-15]
 [ 6.66133815e-16]
 [ 8.88178420e-16]
 [-1.33226763e-15]
 [-1.11022302e-15]
 [ 2.22044605e-16]
 [-2.42861287e-15]]
