In [1]:
import numpy as np

In [2]:
def operacionFila(A,fil_m,fil_piv,factor):
    A[fil_m,:]=A[fil_m,:]-factor*A[fil_piv,:]

In [3]:
def escalonaSimple(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [6]:
A = np.array([[2,3,-1],
              [0,5,4],
              [0,0,6]])
b = np.array([-7,2,18])

#x = np.linalg.solve(A,b)
#print(x)

print(A)
print(b)

[[ 2  3 -1]
 [ 0  5  4]
 [ 0  0  6]]
[-7  2 18]


In [5]:
def sustRegresiva(A,b):     #Resuelve un sistema escalonado
    N=b.shape[0]   #A y b deben ser array numpy bidimensional
    x=np.zeros((N,1))
    for i in range(N-1,-1,-1):
        x[i,0]=(b[i,0]-np.dot(A[i,i+1:N],x[i+1:N,0]))/A[i,i]    
    return x #arra bidimensional


In [4]:
def Gausselimsimple(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaSimple(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(A1,b1)
    return x #array bidimensional

In [11]:
def intercambiFilas(A,fil_i,fil_j):
    A[[fil_i,fil_j],:]=A[[fil_j,fil_i],:]

In [12]:
def escalonaWithPiv(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        imax=np.argmax(np.abs(A[j:nfil,j]))
        intercambiFilas(A,j+imax,j)
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [ ]:
def GaussElimwithpiv(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaWithPiv(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(

In [7]:
import numpy as np
#import libreria as lib
A=np.random.rand(4,4)
#print(A)
b=np.random.rand(4,1)
#print(b)
sol=Gausselimsimple(A,b)
print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)


Solution: 
[[ 2.89136823]
 [ 2.56579975]
 [-6.27948554]
 [ 0.10026426]]

 Residuo:
 [[4.44089210e-16]
 [0.00000000e+00]
 [3.33066907e-16]
 [1.11022302e-15]]


In [9]:
import numpy as np
import time
#import libreria as lib
n=13
A=np.random.rand(n,n)
#print(A)
b=np.random.rand(n,1)
#print(b)

start_time=time.perf_counter()
sol=Gausselimsimple(A,b)
end_time=time.perf_counter()
elapsed_time=end_time-start_time
print(f"Elapsed time: {elapsed_time:.4f} seconds")

print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)

Elapsed time: 0.0010 seconds
Solution: 
[[-0.23148186]
 [ 0.44029287]
 [ 0.48768116]
 [ 0.30113042]
 [-0.57332549]
 [-1.89052539]
 [ 0.62840581]
 [ 1.18529283]
 [ 0.56179551]
 [ 0.10446376]
 [-0.34591334]
 [ 0.60780523]
 [-0.57001744]]

 Residuo:
 [[ 0.00000000e+00]
 [-3.33066907e-16]
 [ 6.66133815e-16]
 [ 6.66133815e-16]
 [-1.66533454e-15]
 [ 1.33226763e-15]
 [-2.10942375e-15]
 [-3.33066907e-16]
 [-5.55111512e-16]
 [-1.22124533e-15]
 [ 1.55431223e-15]
 [-1.66533454e-15]
 [ 9.99200722e-16]]


In [ ]:
n=180
A=np.random.rand(n,n)
b=np.random.rand(n,1)

X=GaussFilaSimple(A,b)
normErr1=np.linalg.norm(A@X-b,1)

X=Gausselimsimple(A,b)
normErr2=np.linalg.norm(A@X-b,1)