In [9]:
import numpy as np

In [10]:
def operacionFila(A,fil_m,fil_piv,factor):
    A[fil_m,:]=A[fil_m,:]-factor*A[fil_piv,:]

In [11]:
def escalonaSimple(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [12]:
A = np.array([[2,3,-1],
              [0,5,4],
              [0,0,6]])
b = np.array([-7,2,18])

#x = np.linalg.solve(A,b)
#print(x)

print(A)
print(b)

[[ 2  3 -1]
 [ 0  5  4]
 [ 0  0  6]]
[-7  2 18]


In [13]:
def sustRegresiva(A,b):     #Resuelve un sistema escalonado
    N=b.shape[0]   #A y b deben ser array numpy bidimensional
    x=np.zeros((N,1))
    for i in range(N-1,-1,-1):
        x[i,0]=(b[i,0]-np.dot(A[i,i+1:N],x[i+1:N,0]))/A[i,i]    
    return x #arra bidimensional


In [14]:
def Gausselimsimple(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaSimple(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(A1,b1)
    return x #array bidimensional

In [15]:
import numpy as np
#import libreria as lib
A=np.random.rand(4,4)
#print(A)
b=np.random.rand(4,1)
#print(b)
sol=Gausselimsimple(A,b)
print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)



Solution: 
[[ 0.74572515]
 [ 0.46234505]
 [ 0.62539892]
 [-0.83459415]]

 Residuo:
 [[5.55111512e-17]
 [3.55271368e-15]
 [8.32667268e-15]
 [6.77236045e-15]]


In [16]:
import numpy as np
import time
#import libreria as lib
n=13
A=np.random.rand(n,n)
#print(A)
b=np.random.rand(n,1)
#print(b)

start_time=time.perf_counter()
sol=Gausselimsimple(A,b)
end_time=time.perf_counter()
elapsed_time=end_time-start_time
print(f"Elapsed time: {elapsed_time:.4f} seconds")

print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)

Elapsed time: 0.0009 seconds
Solution: 
[[ 0.26472649]
 [ 0.53588647]
 [ 2.21196875]
 [-2.15616749]
 [-1.090557  ]
 [ 2.43249876]
 [-0.15996568]
 [-1.0990051 ]
 [ 2.41728099]
 [-0.14751694]
 [-1.56096505]
 [-0.33453648]
 [ 0.16156848]]

 Residuo:
 [[ 0.00000000e+00]
 [-2.66453526e-15]
 [-2.22044605e-15]
 [-2.88657986e-15]
 [-6.10622664e-15]
 [ 1.44328993e-15]
 [-1.50157664e-14]
 [-6.82787160e-15]
 [ 4.44089210e-16]
 [-1.48214774e-14]
 [-5.66213743e-15]
 [ 4.55191440e-15]
 [ 3.05311332e-15]]
