In [1]:
import numpy as np

In [2]:
def operacionFila(A,fil_m,fil_piv,factor):
    A[fil_m,:]=A[fil_m,:]-factor*A[fil_piv,:]

In [4]:
def escalonaSimple(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [5]:
A = np.array([[2,3,-1],
              [0,5,4],
              [0,0,6]])
b = np.array([-7,2,18])

#x = np.linalg.solve(A,b)
#print(x)

print(A)
print(b)

[[ 2  3 -1]
 [ 0  5  4]
 [ 0  0  6]]
[-7  2 18]


In [7]:
def sustRegresiva(A,b):     #Resuelve un sistema escalonado
    N=b.shape[0]   #A y b deben ser array numpy bidimensional
    x=np.zeros((N,1))
    for i in range(N-1,-1,-1):
        x[i,0]=(b[i,0]-np.dot(A[i,i+1:N],x[i+1:N,0]))/A[i,i]    
    return x #arra bidimensional


In [9]:
def Gausselimsimple(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaSimple(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(A1,b1)
    return x #array bidimensional

In [10]:
def intercambiFilas(A,fil_i,fil_j):
    A[[fil_i,fil_j],:]=A[[fil_j,fil_i],:]

In [11]:
def escalonaWithPiv(A):
    nfil=A.shape[0]
    ncol=A.shape[1]

    for j in range(0,nfil):
        imax=np.argmax(np.abs(A[j:nfil,j]))
        intercambiFilas(A,j+imax,j)
        for i in range(j+1,nfil):
            factor=A[i,j]/A[j,j]
            operacionFila(A,i,j,factor)

In [12]:
def GaussElimwithpiv(A,b):
    Ab=np.append(A,b,axis=1)
    escalonaWithPiv(Ab)
    A1=Ab[:,0:Ab.shape[1]-1].copy()
    b1=Ab[:,Ab.shape[1]-1].copy()
    b1=b1.reshape(b.shape[0],1)
    x=sustRegresiva(A1,b1)
    return x #array bidimensional

In [13]:
import numpy as np
#import libreria as lib
A=np.random.rand(4,4)
#print(A)
b=np.random.rand(4,1)
#print(b)
sol=Gausselimsimple(A,b)
print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)


Solution: 
[[-1.36622549]
 [ 1.87887345]
 [-0.72894395]
 [ 1.19885292]]

 Residuo:
 [[ 0.00000000e+00]
 [-4.21884749e-15]
 [ 1.08801856e-14]
 [ 3.33066907e-15]]


In [15]:
import numpy as np
import time
#import libreria as lib
n=13
A=np.random.rand(n,n)
#print(A)
b=np.random.rand(n,1)
#print(b)

start_time=time.perf_counter()
sol=Gausselimsimple(A,b)
end_time=time.perf_counter()
elapsed_time=end_time-start_time
print(f"Elapsed time: {elapsed_time:.4f} seconds")

print("Solution: ")
print(sol)
residuo=A@sol-b
print("\n Residuo:\n", residuo)

Elapsed time: 0.0006 seconds
Solution: 
[[-0.4338995 ]
 [ 1.26455248]
 [ 0.61419106]
 [-0.97878644]
 [-1.3691956 ]
 [-1.5643662 ]
 [ 2.59576566]
 [-1.59615026]
 [ 2.48732867]
 [-1.23862667]
 [ 1.16360182]
 [ 0.15830978]
 [ 0.05859176]]

 Residuo:
 [[ 4.44089210e-16]
 [ 1.04083409e-16]
 [-1.38777878e-16]
 [ 4.44089210e-16]
 [ 1.11022302e-16]
 [ 2.77555756e-15]
 [ 1.88737914e-15]
 [-3.44169138e-15]
 [-2.17881269e-15]
 [ 2.94209102e-15]
 [ 8.10462808e-15]
 [-8.77076189e-15]
 [-4.44089210e-16]]


In [16]:
n=180
A=np.random.rand(n,n)
b=np.random.rand(n,1)

X=GaussElimwithpiv(A,b)
normErr1=np.linalg.norm(A@X-b,1)

X=Gausselimsimple(A,b)
normErr2=np.linalg.norm(A@X-b,1)

X=np.linalg.solve(A,b)
normErr3=np.linalg.norm(A@X-b,1)



In [ ]:
def LUdecomposition(A):
    nrows=A.shape[0]
    
    U=A.copy()
    L=np.eye(nrows,nrows,dtype=np.float64)
    for col in range(0,nrows-1):
        for row in range(col+1,nrows):
            factor=U[row,col]/U[col,col]
            L[row,col]=factor
            operacionFila(U,row,col,factor)
    return L,U

            