In [1]:
import numpy as np
A=np.random.rand(4,5)
print(A)

[[0.20651644 0.20828942 0.32983286 0.47009212 0.99925452]
 [0.91788147 0.38779021 0.38169375 0.23824321 0.42803407]
 [0.32289123 0.91996518 0.41650549 0.2114082  0.437453  ]
 [0.23166264 0.67451137 0.94706563 0.91708445 0.50426945]]


In [3]:
def intercambiFilas(A,fil_i,fil_j):
    A[[fil_i,fil_j],:]=A[[fil_j,fil_i],:]

In [10]:
B=intercambiFilas(A,1,3)
print(A)
print(B)

[[0.800039   0.77990042 0.52163512 0.17430636 0.78862541]
 [0.52273723 0.32687027 0.38070115 0.40532097 0.45421427]
 [0.4937363  0.72433725 0.33996661 0.84454623 0.6171524 ]
 [0.65521163 0.37204252 0.79196566 0.58098129 0.88355901]]
None


In [11]:
def operacionFila(A,fil_m,fil_piv,factor):
    A[fil_m,:]=A[fil_m,:]-factor*A[fil_piv,:]

In [15]:
operacionFila(A,1,1,2)
print(A)

[[ 0.800039    0.77990042  0.52163512  0.17430636  0.78862541]
 [ 1.07734076  1.23293056  0.6625691  -0.05670826  1.12303655]
 [ 0.4937363   0.72433725  0.33996661  0.84454623  0.6171524 ]
 [ 0.65521163  0.37204252  0.79196566  0.58098129  0.88355901]]
