In [1]:
import math

In [2]:
math.gcd(5,6)


1

In [3]:
math.gcd(5,6)

1

In [4]:
math.exp(1)

2.718281828459045

In [5]:
math.exp(2)

7.38905609893065

In [6]:
print("SECCIÓN IMG COMPLETAR")

SECCIÓN IMG COMPLETAR


In [7]:
lista1=[1,"Jorge",True]
print(type(lista1))
print(lista1[0])
print(lista1[1])
print(lista1[2])

<class 'list'>
1
Jorge
True


In [8]:
lista2=[255,"pepe",lista1]
print(lista2[0])
print(lista2[2])
print(lista2[2][2])

255
[1, 'Jorge', True]
True


In [9]:
lista3=[13,26,"Sab",lista2] #NO OFICIAL, ES UNA PRUEBA PARA COMPRENDER
print(type(lista3))
print(lista3[0])
print(lista3[2])
print(lista3[3][2][1])

<class 'list'>
13
Sab
Jorge


In [10]:
## **MÉTODOS Y FUNCIONES PARA LISTAS**
#Un método es una función que "pertenece" a un objeto

In [11]:
edades=[25,23,12,45,13,23]
#edades.sort
edades.sort() #método sort
print(edades)

[12, 13, 23, 23, 25, 45]


In [12]:
edades=[25,23,12,45,13,23]
#edades.sort
edades.sort(reverse=True) #método sort
print(edades)
edades.append(100)
print(edades)
edades.sort()
print(edades)

[45, 25, 23, 23, 13, 12]
[45, 25, 23, 23, 13, 12, 100]
[12, 13, 23, 23, 25, 45, 100]


In [13]:
nombres = ["Carlos", "Ana", "Beatriz","X","F"] # PRUEBA CON LETRAS
nombres.sort(reverse=True)
print(nombres)

['X', 'F', 'Carlos', 'Beatriz', 'Ana']


In [14]:
for X in edades:  #NO OFICIAL PRUEBA
    print(X)

12
13
23
23
25
45
100


In [15]:
print(X)

100


In [16]:
edades.count(23)

2

In [17]:
edades2=[25,23,12,45,13,23]  #
edades3=sorted(edades2,reverse=True)
print(edades3)

[45, 25, 23, 23, 13, 12]


In [18]:
poligonos=["triángulo","cuadrado","trapecio"]
print(poligonos)
poligonos.append("rombo")
print(poligonos)
poligonos.reverse()
print(poligonos)

['triángulo', 'cuadrado', 'trapecio']
['triángulo', 'cuadrado', 'trapecio', 'rombo']
['rombo', 'trapecio', 'cuadrado', 'triángulo']


In [19]:
otros=["hexagono","pentagono"]
poligonos.append(otros)
print(poligonos)
poligonos.insert(2,"rectángulo")
print(poligonos)


['rombo', 'trapecio', 'cuadrado', 'triángulo', ['hexagono', 'pentagono']]
['rombo', 'trapecio', 'rectángulo', 'cuadrado', 'triángulo', ['hexagono', 'pentagono']]


In [20]:
poligonos.remove("cuadrado")
print(poligonos)

['rombo', 'trapecio', 'rectángulo', 'triángulo', ['hexagono', 'pentagono']]


In [21]:
list3=["a","b","c"]
list4=["c","d"]
concat1=list3+list4
print(concat1)
concat2=list4+list3
print(concat2)

['a', 'b', 'c', 'c', 'd']
['c', 'd', 'a', 'b', 'c']


In [22]:
print(list3)
list3[0]=123
print(list3)

['a', 'b', 'c']
[123, 'b', 'c']


In [23]:
## TUPLA
# Estructura similar a la estructura lista, sin embargo es inmutable

In [24]:
tup=("a","b","c")
print(type(tup))
print(tup[0])
tup.index("c")

<class 'tuple'>
a


2

In [25]:
print("Esto",tup,"es una tupla")

Esto ('a', 'b', 'c') es una tupla


In [26]:
# RANGO

RANGO

In [27]:
sucesion=range(7)
print(type(sucesion))
print(sucesion)
print(sucesion[0])
print(sucesion[1])
print(sucesion[2])
print(sucesion[3])
print(sucesion[6])
print("El objeto sucesion tiene", len(sucesion), "elementos")

<class 'range'>
range(0, 7)
0
1
2
3
6
El objeto sucesion tiene 7 elementos


In [28]:
rango=range(3,7)
print(rango)
print(list(rango))  #add
print(rango[0])
print(rango[1])
print(rango[2])
print(rango[3])
print(rango.stop)

range(3, 7)
[3, 4, 5, 6]
3
4
5
6
7


In [29]:
rango2=range(3,7,2)
print(rango2)
print(rango2[0])
print(rango2[1])

for n in rango2:  #ADD
    print(n)

range(3, 7, 2)
3
5
3
5


In [30]:
lista3=[13,26,"Sab","lista2"] #NO OFICIAL, ES UNA PRUEBA PARA COMPRENDER
print(type(lista3))
print(lista3[0])
print(lista3[2])
print(lista3[3])

<class 'list'>
13
Sab
lista2


In [31]:
for x in lista3:
    print(x)

13
26
Sab
lista2


In [32]:
lista3.append("gg")

In [33]:
for y in lista3:
    print(y)

13
26
Sab
lista2
gg


SABADO 13 DE SETIEMBRE

In [34]:
import array

In [35]:
from array import array

In [36]:
a=array('l',[-1,3,-3,-4,-5])
print(a)
print(type(a))
print("longitud de a:",len(a))
print(a[0])
# print(a[1])
print(a[2])
print(a[3])
print(a[4])
suma=a[0]+a[4]
print("suma=",suma)
#b=array()

array('l', [-1, 3, -3, -4, -5])
<class 'array.array'>
longitud de a: 5
-1
-3
-4
-5
suma= -6


In [37]:
import array as arr
numbers = arr.array('i',[10,20,30])
type(numbers)

array.array

## Conjunto (set)
Estructura de datos con almacenamiento y operaciones similar al de los conjuntos matemáticos.
[Referencia](https://www.w3schools.com/python/python_sets.asp)

In [38]:
A1={"rojo","verde","azul"}
A2={"verde","negro","amarillo"}
print(type(A1))
print(A1)

<class 'set'>
{'rojo', 'verde', 'azul'}


In [39]:
A3=A1.intersection(A2)
A4=A2.intersection(A1)
print(type(A3))
print(A3)
print(A4)

<class 'set'>
{'verde'}
{'verde'}


In [40]:
A5=A1.difference(A2) 
print(A5)
A1.isdisjoint(A2)
respuesta=A1.isdisjoint(A3)  #Es disjunto?
print(respuesta)

{'rojo', 'azul'}
False


In [41]:
Valor=A1.__contains__("verde") #pertenece
print(Valor)

True


In [42]:
C=set([range(4,7),"hola",23])
print(type(C))
print(C)

<class 'set'>
{'hola', range(4, 7), 23}


In [43]:
D={"Jorge","Pedro","Juan","Hector"}
D.pop()
print(D)


{'Pedro', 'Jorge', 'Juan'}


In [44]:
D.pop()
print(D)
D.pop()
print(D)
D.pop()
print(D)
D.add(24)
print(D)

{'Jorge', 'Juan'}
{'Juan'}
set()
{24}


In [45]:
E={"Jorge","Pedro","Juan","Hector"}
for i in E:
    print(i)

Hector
Pedro
Jorge
Juan


In [51]:
import numpy as np
mat1=np.array({1,2,3})
print(type(mat1))
print(mat1)


<class 'numpy.ndarray'>
{1, 2, 3}


In [ ]:
mat2=np.array([[1,2,3],[4,5,6]])
print(mat2)
print(mat2.shape)
print(mat2.nbytes)
print(mat2.max())
mat2.T


[[1 2 3]
 [4 5 6]]
(2, 3)
48
6


array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
(mat2[0,0]+mat2[0,2])*mat2[1,1]

np.int64(20)

In [79]:
matriz=np.array([[1.,2.,3.],[4.,5.,6.],[7,8,9]])
print(matriz)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [80]:
print(matriz[0,0],matriz[1,1],matriz[2,2])
Tr=matriz[0,0]+matriz[1,1]+matriz[2,2]
print(Tr)

1.0 5.0 9.0
15.0


In [81]:
Trz=np.trace(matriz)
print(Trz)

15.0


In [82]:
print(matriz.T)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [85]:
print(matriz.argmax())
print(matriz.argmin())
print(matriz.any())
print(matriz.all())
print(matriz.diagonal())
print(matriz.mean())
print(np.linalg.det(matriz))

8
0
True
True
[1. 5. 9.]
5.0
0.0


In [87]:
matriz2=np.array([[9.,8.,7.],[6.,5.,4.],[3.,2.,1.]])
print(matriz2)

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [107]:
print(matriz+matriz2)
print(matriz@matriz2)
print(matriz*matriz2)
print(np.dot(matriz,matriz2))
print(np.matmul(matriz,matriz2))

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]
[[ 9. 16. 21.]
 [24. 25. 24.]
 [21. 16.  9.]]
[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]
[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


In [ ]:
print(np.sum(matriz))
print(np.sum(matriz,axis=0))
print(np.sum(matriz,axis=1))

45.0
[12. 15. 18.]
[ 6. 15. 24.]


In [102]:
print(matriz.dtype)
matriz3=np.array([[1.,2.,3.],[5.,6.,7.],[8.,9.,10.]],dtype=np.float64)
matriz3T=matriz3.T
print(matriz3T)

float64
[[ 1.  5.  8.]
 [ 2.  6.  9.]
 [ 3.  7. 10.]]


In [104]:
print(np.trace(matriz3))
print(matriz3.trace())

17.0
17.0


In [114]:
matt1=np.zeros((2,3),dtype=np.int32)
print("matriz:\n",matt1)
matt2=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
print(matt2)
print("matriz:\n",matt1)
print("Dimensiones:",matt1.ndim)
print("Forma:",matt1.shape)
print("Tipo:",matt1.dtype)


matriz:
 [[0 0 0]
 [0 0 0]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
matriz:
 [[0 0 0]
 [0 0 0]]
Dimensiones: 2
Forma: (2, 3)
Tipo: int32


In [118]:
matt2=np.empty((3,3),dtype=np.float32)
print(matt2)

[[ 0.0000000e+00  0.0000000e+00 -1.2652364e-16]
 [ 4.6943499e-43 -1.2656176e-16  4.6943499e-43]
 [-1.2656282e-16  4.6943499e-43  0.0000000e+00]]
